version: "3.2"
services:
  app:
    container_name: app
    image: starsaminf/reactjs:docker-compose
    networks:
      - back
    volumes:
     - app-data:/src
    working_dir: /src
    restart: always
    ports:
      - "3000:3000"
    command: npm start --progress --host 0.0.0.0
    tty: true
  
  mongo:
    container_name: mongo
    image: mongo
    networks:
      - back
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

networks:
  back:
    driver: bridge 

volumes:
  app-data:
    driver: local
    driver_opts:
      device: $PWD
      o: bind
      type: none

  mongo-data:
    driver: local
    driver_opts:
      device: $PWD/data
      o: bind
      type: none
